name: CI
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      # Install, should be basically instant if cached
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Verify dependencies are hooked up right
      - run: node test/verifyPackageVersions.js

      # Grab localizations
      - run: yarn docs-sync pull microsoft/TypeScript-Website-localizations#main 1

      # Build the packages
      - run: yarn bootstrap
      - run: yarn build

      # Verify it compiles
      - run: yarn build-site
      
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: site
          path: packages/typescriptlang-org/public

      # Run all the package's tests
      - run: yarn test
        env:
          CI: true

      # danger for PR builds
      - if: github.event_name == 'pull_request' && github.event.pull_request.base.repo.id == github.event.pull_request.head.repo.id
        run: "yarn danger ci"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          git add .
          if ! git diff --staged --exit-code --quiet; then
            echo "This PR is missing some generated changes. Please update locally or merge the patch artifact."
            echo ""
            git diff --staged
            git diff --staged > missing.patch
            exit 1
          fi
        name: Check for uncommitted changes
        id: check-diff
        if: github.event_name == 'pull_request'

      - name: Upload diff artifact
        if: ${{ failure() && steps.check-diff.conclusion == 'failure' }}
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: missing.patch
          path: missing.patch

  windows:
    runs-on: windows-latest

    steps:
      # Check out, and set up the node infra
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      # Get local dependencies
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      - run: yarn bootstrap
      - run: yarn build
