name: deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  trigger_another_repo_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: sync
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git config user.name "SyncDocsBot"
        git config user.email "tsdocs@126.com"
        git commit --allow-empty -m "sync"
        git push https://github.com/ts-zh-docs/TypeScript-Website.git HEAD:v2
